
version: '3.8'

services:
  smtp-server:
    build: .
    ports:
      - "25:25"
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./config:/app/config
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - smtp-server
