version: '3.8'

services:
  app:
    build:
      context: .  # Root directory where the combined Dockerfile exists
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Frontend (Vite development server)
      - "8000:8000"  # Backend (FastAPI server)
      - "1000:1000"  # Render's default port for hosting
    volumes:
      - ./frontend:/app/frontend
      - ./backend:/app/backend
    environment:
      # Frontend-specific settings
      - CHOKIDAR_USEPOLLING=true

      # Backend-specific settings
      - UVLOOP=1
    stdin_open: true
    command: |
      sh -c "cd /app/backend && uvicorn src.chatbot:app --host 0.0.0.0 --port 8000 & 
             cd /app/frontend && npm run dev"
