version: '3.8'
services:
  app:
    build:
      context: .  # Root directory where both frontend and backend reside
      dockerfile: Dockerfile  # Use the combined Dockerfile
    ports:
      - "5173:5173"  # Frontend port (Vite)
      - "1000:1000"  # Backend port (Express HTTP server)
    volumes:
      - ./frontend:/app/frontend  # Mount frontend for live reload
      - ./backend:/app/backend    # Mount backend for live reload
    environment:
      - CHOKIDAR_USEPOLLING=true  # For live reload on Windows
    stdin_open: true  # To keep container interactive
    command: bash -c "npm --prefix /app/frontend run dev & node /app/backend/server.js"  # Run both frontend and backend
