version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Enable live reload for backend
    environment:
      - UVLOOP=1  # Use uvloop for FastAPI
    command: uvicorn src.chatbot:app --host 0.0.0.0 --port 8000 --loop uvloop

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app  # Enable live reload for frontend
      - /app/node_modules
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true  # Required for live reload in Docker
