
smtp:
  host: 0.0.0.0
  port: 25
  max_connections: 100
  timeout: 300

security:
  tls_required: true
  allowed_domains:
    - example.com
    - localhost

logging:
  level: INFO
  file: /var/log/smtp-server.log

spam_filter:
  enabled: true
  threshold: 5.0

authentication:
  method: local  # options: local, ldap, oauth
  max_login_attempts: 3
